<a href="https://colab.research.google.com/github/Gun-Ho-Lee1106/Python-project/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

train_df = pd.read_csv('/content/drive/MyDrive/sparta_club/train.csv')
test_df = pd.read_csv('/content/drive/MyDrive/sparta_club/test.csv')

In [38]:
train_df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [39]:
train_df.shape

(891, 12)

In [40]:
test_df.shape

(418, 11)

In [41]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [42]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [43]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


#필요없는 열 삭제

In [44]:
del train_df['PassengerId']
del train_df['Name']
del train_df['Ticket']
del train_df['Cabin']

In [45]:
del test_df['PassengerId']
del test_df['Name']
del test_df['Ticket']
del test_df['Cabin']

In [46]:
print(train_df)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]


#결측치 처리

In [47]:
train_df.loc[train_df['Sex'] == 'female', 'Age'] = train_df.loc[train_df['Sex'] == 'female', 'Age'].fillna(
    train_df[train_df['Sex'] == 'female']['Age'].mean()
)

In [48]:
train_df.loc[train_df['Sex'] == 'male', 'Age'] = train_df.loc[train_df['Sex'] == 'male', 'Age'].fillna(
    train_df[train_df['Sex'] == 'male']['Age'].mean()
)

In [49]:
test_df.loc[test_df['Sex'] == 'female', 'Age'] = test_df.loc[test_df['Sex'] == 'female', 'Age'].fillna(
    test_df[test_df['Sex'] == 'female']['Age'].mean()
)

In [50]:
test_df.loc[test_df['Sex'] == 'male', 'Age'] = test_df.loc[test_df['Sex'] == 'male', 'Age'].fillna(
    test_df[test_df['Sex'] == 'male']['Age'].mean()
)

In [51]:
train_df['Embarked'] = train_df['Embarked'].fillna(train_df['Embarked'].value_counts().index[0])

In [52]:
test_df['Embarked'] = test_df['Embarked'].fillna(test_df['Embarked'].value_counts().index[0])

범주형 데이터 처리

In [53]:
train_df['Sex'] = train_df['Sex'].replace(['female','male'],[0, 1])

<ipython-input-53-fe4a3aafb710>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_df['Sex'] = train_df['Sex'].replace(['female','male'],[0, 1])


In [54]:
test_df['Sex'] = train_df['Sex'].replace(['female','male'],[0, 1])

In [55]:
train_df['Pclass'] = train_df['Pclass'].astype('category')

In [56]:
train_df['Embarked'] = train_df['Embarked'].astype('category')

In [57]:
test_df['Pclass'] = test_df['Pclass'].astype('category')

In [58]:
test_df['Embarked'] = test_df['Embarked'].astype('category')

카테고리형 데이터 더미변수변환 또는 원핫 인코딩

In [59]:
train_df = pd.get_dummies(train_df)
test_df = pd.get_dummies(test_df)

In [60]:
train_df.head()

Survived  Sex   Age  SibSp  Parch     Fare  Pclass_1  Pclass_2  Pclass_3  \
0         0    1  22.0      1      0   7.2500     False     False      True   
1         1    0  38.0      1      0  71.2833      True     False     False   
2         1    0  26.0      0      0   7.9250     False     False      True   
3         1    0  35.0      1      0  53.1000      True     False     False   
4         0    1  35.0      0      0   8.0500     False     False      True   

   Embarked_C  Embarked_Q  Embarked_S  
0       False       False        True  
1        True       False       False  
2       False       False        True  
3       False       False        True  
4       False       False        True

In [61]:
test_df.head()

Sex   Age  SibSp  Parch     Fare  Pclass_1  Pclass_2  Pclass_3  Embarked_C  \
0    1  34.5      0      0   7.8292     False     False      True       False   
1    0  47.0      1      0   7.0000     False     False      True       False   
2    0  62.0      0      0   9.6875     False      True     False       False   
3    0  27.0      0      0   8.6625     False     False      True       False   
4    1  22.0      1      1  12.2875     False     False      True       False   

   Embarked_Q  Embarked_S  
0        True       False  
1       False        True  
2        True       False  
3       False        True  
4       False        True

In [62]:
x_data=train_df.iloc[:,1:]
print(x_data.head())

   Sex   Age  SibSp  Parch     Fare  Pclass_1  Pclass_2  Pclass_3  Embarked_C  \
0    1  22.0      1      0   7.2500     False     False      True       False   
1    0  38.0      1      0  71.2833      True     False     False        True   
2    0  26.0      0      0   7.9250     False     False      True       False   
3    0  35.0      1      0  53.1000      True     False     False       False   
4    1  35.0      0      0   8.0500     False     False      True       False   

   Embarked_Q  Embarked_S  
0       False        True  
1       False       False  
2       False        True  
3       False        True  
4       False        True  


In [63]:
y_data =train_df['Survived']
print(y_data.head())

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64


In [64]:
# 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)

In [65]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [72]:
Logistic_model = LogisticRegression()
Logistic_model.fit(x_train, y_train)

LogisticRegression()

In [73]:
# 예측
Logistic_pred = Logistic_model.predict(x_test)

# 평가
print(f"Logistic Accuracy: {accuracy_score(y_test, Logistic_pred)}")
print(f"Classification Report:\n{classification_report(y_test, Logistic_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, Logistic_pred)}")

Logistic Accuracy: 0.7988826815642458
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.86      0.83       105
           1       0.78      0.72      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

Confusion Matrix:
[[90 15]
 [21 53]]


In [79]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear')
svm_model.fit(x_train, y_train)

SVC(kernel='linear')

In [80]:
#예측
svm_pred =svm_model.predict(x_test)
# 평가
print(f"svm Accuracy: {accuracy_score(y_test, svm_pred)}")
print(f"Classification Report:\n{classification_report(y_test, svm_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, svm_pred)}")

Logistic Accuracy: 0.7821229050279329
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.84      0.82       105
           1       0.75      0.70      0.73        74

    accuracy                           0.78       179
   macro avg       0.78      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179

Confusion Matrix:
[[88 17]
 [22 52]]


In [81]:
from sklearn.neighbors import KNeighborsClassifier
Knn_model = KNeighborsClassifier(n_neighbors=5)
Knn_model.fit(x_train, y_train)

KNeighborsClassifier()

In [82]:
#예측
Knn_pred =Knn_model.predict(x_test)
# 평가
print(f"KNN Accuracy: {accuracy_score(y_test,Knn_pred)}")
print(f"Classification Report:\n{classification_report(y_test, Knn_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, Knn_pred)}")

KNN Accuracy: 0.8268156424581006
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       105
           1       0.81      0.76      0.78        74

    accuracy                           0.83       179
   macro avg       0.82      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

Confusion Matrix:
[[92 13]
 [18 56]]


In [88]:
from sklearn.naive_bayes import GaussianNB
GaussianNB_model = GaussianNB()
GaussianNB_model.fit(x_train, y_train)

GaussianNB()

In [92]:
#예측
GaussianNB_pred = GaussianNB_model.predict(x_test)
# 평가
print(f"GaussianNB Accuracy: {accuracy_score(y_test,GaussianNB_pred)}")
print(f"Classification Report:\n{classification_report(y_test,GaussianNB_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test,GaussianNB_pred)}")

GaussianNB Accuracy: 0.770949720670391
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.79      0.80       105
           1       0.71      0.74      0.73        74

    accuracy                           0.77       179
   macro avg       0.76      0.77      0.77       179
weighted avg       0.77      0.77      0.77       179

Confusion Matrix:
[[83 22]
 [19 55]]


In [94]:
from sklearn.tree import DecisionTreeClassifier
DT_model = DecisionTreeClassifier(random_state=42)
DT_model.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [95]:
#예측
DT_model_pred= DT_model.predict(x_test)
# 평가
print(f"DT_model_pred Accuracy: {accuracy_score(y_test,DT_model_pred)}")
print(f"Classification Report:\n{classification_report(y_test,DT_model_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test,DT_model_pred)}")

DT_model_pred Accuracy: 0.776536312849162
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.81      0.81       105
           1       0.73      0.73      0.73        74

    accuracy                           0.78       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179

Confusion Matrix:
[[85 20]
 [20 54]]
